# Generated by Django 2.2.13 on 2020-10-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(null=True)),
                ('image', models.CharField(max_length=200)),
                ('release_date', models.DateField(blank=True)),
                ('lte_exists', models.BooleanField(default=False)),
                ('slug', models.SlugField(allow_unicode=True)),
            ],
        ),
    ]
