# Generated by Django 2.2.10 on 2020-10-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201025_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(through='articles.Scope', to='articles.Article'),
        ),
    ]
