# Generated by Django 3.1.2 on 2020-11-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.ImageField(blank=True, upload_to='sensors/%Y/%m/%d/'),
        ),
    ]
