# Generated by Django 3.1.2 on 2020-11-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_auto_20201111_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sensors/%Y/%m/%d/'),
        ),
    ]
