# Generated by Django 3.1.2 on 2020-11-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_auto_20201111_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='sensors/%Y/%m/%d/'),
        ),
    ]
